// examples/sample-react-app/src/pages/Checkout.tsx
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

export default function Checkout() {
  const navigate = useNavigate()
  const { isAuthenticated } = useAuth()

  if (!isAuthenticated) {
    navigate('/login')
  }

  return (
    <div>
      <h1>Checkout</h1>
      <button onClick={() => navigate('/')}>Place order</button>
    </div>
  )
}

// examples/sample-angular-app/src/checkout.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-checkout',
  standalone: true,
  template: `
    <h1>Checkout</h1>
    <button (click)="complete()">Complete order</button>
  `,
})
export class CheckoutComponent {
  constructor(private router: Router) {}

  complete(): void {
    this.router.navigate(['/'])
  }
}
