// examples/sample-react-app/src/pages/Dashboard.tsx
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

export default function Dashboard() {
  const { isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  if (!isAuthenticated) {
    navigate('/login')
  }

  return (
    <div>
      <h1>Dashboard</h1>
      <Link to="/dashboard/settings">Settings</Link>
      <NavLink to="/products">Products</NavLink>
      <button
        onClick={() => {
          logout()
          navigate('/')
        }}
      >
        Logout
      </button>
    </div>
  )
}

// examples/sample-angular-app/src/dashboard.component.ts
import { Component } from '@angular/core'
import { Router, RouterLink } from '@angular/router'

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [RouterLink],
  template: `
    <h1>Dashboard</h1>
    <nav>
      <a routerLink="/dashboard/settings">Settings</a>
      <a routerLink="/products">Products</a>
    </nav>
    <button (click)="logout()">Log out</button>
  `,
})
export class DashboardComponent {
  constructor(private router: Router) {}

  logout(): void {
    this.router.navigate(['/'])
  }
}
