// examples/sample-react-app/src/pages/Login.tsx
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

export default function Login() {
  const navigate = useNavigate()
  const { login } = useAuth()

  function onSubmit() {
    login()
    navigate('/dashboard')
  }

  return (
    <div>
      <h1>Login</h1>
      <button onClick={onSubmit}>Sign in</button>
    </div>
  )
}

// examples/sample-angular-app/src/login.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-login',
  standalone: true,
  template: `
    <h1>Login</h1>
    <button (click)="submit()">Sign in</button>
  `,
})
export class LoginComponent {
  constructor(private router: Router) {}

  submit(): void {
    this.router.navigate(['/dashboard'])
  }
}
