// examples/sample-react-app/src/pages/ProductDetail.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function ProductDetail() {
  const navigate = useNavigate()
  const [hovered, setHovered] = useState(false)
  return (
    <div>
      <h1>Product</h1>
      <button aria-pressed={hovered} onClick={() => navigate('/checkout')} onMouseEnter={() => setHovered(true)}>
        Buy
      </button>
    </div>
  )
}

// examples/sample-angular-app/src/product-detail.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-product-detail',
  standalone: true,
  template: `
    <h1>Product Detail</h1>
    <button (click)="buy()">Buy now</button>
  `,
})
export class ProductDetailComponent {
  constructor(private router: Router) {}

  buy(): void {
    this.router.navigate(['/checkout'])
  }
}
