// examples/sample-react-app/src/pages/Dashboard.tsx
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth'

export default function Dashboard() {
  const { isAuthenticated, logout } = useAuth()
  const navigate = useNavigate()

  if (!isAuthenticated) {
    navigate('/login')
  }

  return (
    <div>
      <h1>Dashboard</h1>
      <Link to="/dashboard/settings">Settings</Link>
      <NavLink to="/products">Products</NavLink>
      <button
        onClick={() => {
          logout()
          navigate('/')
        }}
      >
        Logout
      </button>
    </div>
  )
}

// examples/sample-vue-app/src/pages/Dashboard.vue
<template>
  <main>
    <h1>Dashboard</h1>
    <router-link to="/products">Products</router-link>
    <button @click="goSettings">Settings</button>
  </main>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'Dashboard',
  methods: {
    goSettings(): void {
      this.$router.push('/dashboard/settings')
    },
  },
})
</script>
