// examples/sample-angular-app/src/login.component.ts
import { Component } from '@angular/core'
import { Router } from '@angular/router'

@Component({
  selector: 'app-login',
  standalone: true,
  template: `
    <h1>Login</h1>
    <form (submit)="submit()">
      <input type="email" name="email" required (input)="onEmail($event)" />
      <button data-testid="login-submit" (click)="submit()">Sign in</button>
    </form>
  `,
})
export class LoginComponent {
  constructor(private router: Router) {}

  onEmail(_event: Event): void {}

  submit(): void {
    this.router.navigate(['/dashboard'])
  }
}

// examples/sample-vue-app/src/pages/Login.vue
<template>
  <main>
    <h1>Login</h1>
    <form @submit.prevent="submit">
      <input type="email" name="email" required @input="onEmail" />
      <button data-testid="login-submit" @click="submit">Sign in</button>
    </form>
  </main>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'

const router = useRouter()

function onEmail(_event: Event): void {}

function submit(): void {
  router.push('/dashboard')
}
</script>
